# Generated by Django 4.2.13 on 2024-05-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Цена')),
                ('size', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Участок',
                'verbose_name_plural': 'Участки',
                'db_table': 'plot',
            },
        ),
    ]
